# This is a config for E2B sandbox template.
# You can use template ID (kqnfcqg68j8appy0tsv8) or template name (frame-nextjs-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("frame-nextjs-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("frame-nextjs-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('frame-nextjs-template')

team_id = "6f3bef96-8ad6-452c-9961-9d840b9cd841"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "frame-nextjs-template"
template_id = "kqnfcqg68j8appy0tsv8"
